name = "ganga-seva-sangat"
main = "src/index.ts"
compatibility_date = "2026-09-05"

[[d1_databases]]
binding = "DB"
database_name = "gss_core_circle_alerts"
migrations_dir = "db/migrations"
database_id = "59f4d1ce-c60e-494a-9cbe-88db4e959361"

[vars]
APP_ORIGIN = "https://alert.gangasevasangat.com"
